services:
  devopspalermo:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./devops_palermo.db:/app/devops_palermo.db
  prometheus:
    image: prom/prometheus:latest
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

volumes:
  db_data:
