# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      needs: build_and_test
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
  
      steps:
        - name: Check out repo
          uses: actions/checkout@v3
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ${{ github.repository }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USER }}/user-service:${{ github.sha }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              DB_HOST=${{ secrets.DB_HOST }}
              DB_USER=${{ secrets.DB_USER }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              DB_DATABASE=${{ secrets.DB_DATABASE }}
